name: Poll External Repo
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.cache-hash.outputs.cache-hit != 'true' }} # 結果をjob出力に設定
    steps:
      - name: Get latest commit hash
        id: get-hash
        run: |
          HASH=$(git ls-remote https://github.com/tttmmmyyyy/fixlang.git HEAD | awk '{ print $1 }')
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Restore last hash
        id: cache-hash
        uses: actions/cache@v4
        with:
          path: last_hash.txt
          key: last-hash-${{ steps.get-hash.outputs.hash }}

      - name: Save current hash
        if: steps.cache-hash.outputs.cache-hit != 'true'
        run: echo "${{ steps.get-hash.outputs.hash }}" > last_hash.txt

  # 差分がある場合のみ、別のワークフローを呼び出す
  call-build:
    needs: check
    if: needs:check.outputs.changed == 'true'
    uses: ./.github/workflows/build.yml # 同じリポジトリ内のファイルを指定
    secrets: inherit # 親のSecrets（DockerHubの鍵など）を子に引き継ぐ
