# GitHub では、コミット SHA にアクションをピン留めすることが推奨されます。
# 新しいバージョンを取得するには、SHA を更新する必要があります。
# タグまたはブランチを参照することもできますが、アクションは警告なしに変更される可能性があります。

name: publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: List directory
        run: ls -l
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Dockerレイヤーキャッシュを利用
      # https://dev.classmethod.jp/articles/github-actions-docker-layer-cache-enable/
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker (fixlang)
        id: meta_fixlang
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: pt9999/fixlang
          #images: my-docker-hub-namespace/my-docker-hub-repository

      - name: Build and push Docker image (fixlang)
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./fixlang
          file: ./fixlang/Dockerfile
          push: true
          tags: ${{ steps.meta_fixlang.outputs.tags }}
          labels: ${{ steps.meta_fixlang.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker (fixlang_minilib_ci)
        id: meta_fixlang_minilib_ci
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: pt9999/fixlang_minilib_ci
          #images: my-docker-hub-namespace/my-docker-hub-repository

      - name: Build and push Docker image (fixlang_minilib_ci)
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./fixlang_minilib_ci
          file: ./fixlang_minilib_ci/Dockerfile
          push: true
          tags: ${{ steps.meta_fixlang_minilib_ci.outputs.tags }}
          labels: ${{ steps.meta_fixlang_minilib_ci.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache