# build and push docker image for `fixlang` and `fixlang_minilib_ci`
name: publish

on:
  workflow_dispatch:
    inputs:
      no-cache:
        description: "Build docker images with no cache"
        default: false
        required: false
        type: boolean
  schedule:
    - cron: '15 21 * * *'
    #  minute(0-59), hour(0-23 UTC), day(1-31), month(1-12), dayoftheweek(0-6, 0=sunday)

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: List directory
        run: ls -l

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker (fixlang)
        id: meta_fixlang
        uses: docker/metadata-action@v5
        with:
          images: pt9999/fixlang
          #images: my-docker-hub-namespace/my-docker-hub-repository

      - name: Get commit-sha
        run: curl https://api.github.com/repos/tttmmmyyyy/fixlang/branches/main | jq -r '.commit.sha' > ./fixlang/commit-sha

      - name: Build and push Docker image (fixlang)
        uses: docker/build-push-action@v5
        with:
          context: ./fixlang
          file: ./fixlang/Dockerfile
          push: true
          tags: ${{ steps.meta_fixlang.outputs.tags }}
          labels: ${{ steps.meta_fixlang.outputs.labels }}
          cache-from: type=gha,scope=fixlang
          cache-to: type=gha,mode=max,scope=fixlang
          no-cache: ${{ inputs.no-cache == true }}

      - name: Extract metadata (tags, labels) for Docker (fixlang_minilib_ci)
        id: meta_fixlang_minilib_ci
        uses: docker/metadata-action@v5
        with:
          images: pt9999/fixlang_minilib_ci
          #images: my-docker-hub-namespace/my-docker-hub-repository

      - name: Build and push Docker image (fixlang_minilib_ci)
        uses: docker/build-push-action@v5
        with:
          context: ./fixlang_minilib_ci
          file: ./fixlang_minilib_ci/Dockerfile
          push: true
          tags: ${{ steps.meta_fixlang_minilib_ci.outputs.tags }}
          labels: ${{ steps.meta_fixlang_minilib_ci.outputs.labels }}
          cache-from: type=gha,scope=fixlang_minilib_ci
          cache-to: type=gha,mode=max,scope=fixlang_minilib_ci
          no-cache: ${{ inputs.no-cache == true }}

